name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and run Docker Compose in detached mode
        run: make up-detached

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start SSH agent and add key
        run: |
          eval $(ssh-agent -s)
          echo "${{ secrets.GH_ACTIONS_SSH_KEY }}" | tr -d '\r' | ssh-add - > /dev/null
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock

      - name: Deploy to DigitalOcean
        run: |
          ssh-keyscan 165.227.44.125 >> ~/.ssh/known_hosts
          ssh -o StrictHostKeyChecking=no gh-actions@165.227.44.125 mkdir -p ~/jayplus
          scp -r ./* gh-actions@165.227.44.125:~/jayplus/
          ssh -o StrictHostKeyChecking=no gh-actions@165.227.44.125 "cd ~/jayplus && make up-detached"
