name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and run Docker Compose
        run: make up-detached
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: jayplus-artifact
          path: ./

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: jayplus-artifact
          path: /home/runner/work/jayplus/jayplus-artifact
      - name: Setup SSH and Deploy
        run: |
          echo "Setting up SSH directory and known hosts"
          mkdir -p ~/.ssh
          ssh-keyscan 165.227.44.125 >> ~/.ssh/known_hosts

          echo "Setting up SSH key"
          echo "${{ secrets.GH_ACTIONS_SSH_KEY }}" > gh-actions-ssh-key
          chmod 600 gh-actions-ssh-key

          echo "Copying artifacts"
          scp -r -i gh-actions-ssh-key /home/runner/work/jayplus/jayplus-artifact/* gh-actions@165.227.44.125:~/

          echo "Deploying"
          ssh -i gh-actions-ssh-key gh-actions@165.227.44.125 'cd ~/ && make up-detached'
