name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and run Docker Compose in detached mode
        run: make up-detached
      - name: Archive entire application as an artifact, excluding certain directories
        run: tar --warning=no-file-changed -zcvf jayplus.tar.gz --exclude-from=.tarignore .
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: jayplus-artifact
          path: ./jayplus.tar.gz

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: jayplus-artifact
      - name: Deploy to DigitalOcean Droplet
        run: |
          # Install SSH client
          sudo apt-get install -y openssh-client
          # Add the VM to known hosts
          ssh-keyscan 165.227.44.125 >> ~/.ssh/known_hosts
          # Write GitHub Actions SSH key to disk
          echo "${{ secrets.GH_ACTIONS_SSH_KEY }}" > gh-actions-ssh-key
          chmod 600 gh-actions-ssh-key
          # Copy artifacts to the VM
          scp -i gh-actions-ssh-key jayplus.tar.gz gh-actions@165.227.44.125:~/ 
          # SSH into the VM
          ssh -i gh-actions-ssh-key gh-actions@165.227.44.125 'bash -s' << 'EOF'
            # Unpack the artifacts
            tar -zxvf ~/jayplus.tar.gz -C ~/
            # Navigate to the root directory and run the Makefile (assuming it deploys both backend and frontend)
            cd ~/
            make up-detached
          EOF
