name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and run Docker Compose
        run: make up-detached
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: jayplus-artifact
          path: ./

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: List current directory (Before Download)
        run: ls -la
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: jayplus-artifact
      - name: List current directory (After Download)
        run: ls -la
      - name: Setup SSH and Deploy
        run: |
          sudo apt-get install -y openssh-client
          mkdir -p ~/.ssh
          ssh-keyscan 165.227.44.125 >> ~/.ssh/known_hosts
          echo "${{ secrets.GH_ACTIONS_SSH_KEY }}" > gh-actions-ssh-key
          chmod 600 gh-actions-ssh-key
          # SCP all contents of current directory
          scp -r -i gh-actions-ssh-key ./ gh-actions@165.227.44.125:~/
          ssh -i gh-actions-ssh-key gh-actions@165.227.44.125 'cd ~/ && make up-detached'
